language: java
sudo: false
install:
    - mkdir lib
    - wget "https://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar" -O lib/junit.jar
    - wget "https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" -O lib/hamcrest.jar

jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk7
    - openjdk8
os:
    - linux
